package com.theevilroot.mkv.jdbc

import com.theevilroot.minikeyvalue.gson.MKVGson
import com.theevilroot.minikeyvaluekt.MiniKeyValue
import com.theevilroot.minikeyvaluekt.okhttp.MKVOkHttp
import java.sql.*
import java.util.*
import java.util.concurrent.Executor
import javax.naming.OperationNotSupportedException

class MkvConnection(private val masterUri: String) : Connection {

    private var readOnly: Boolean = false
    private var networkTimeout: Int = 30
    private val miniKeyValue = MiniKeyValue(masterUri, MKVOkHttp, MKVGson)

    internal fun checkMasterConnection() {
        TODO("Check master connection")
    }

    override fun createStatement(): Statement {
        return MkvStatement(miniKeyValue)
    }


    override fun close() {
        TODO("Not yet implemented")
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement {
        TODO("Not yet implemented")
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(sql: String?): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareStatement(sql: String?, columnNames: Array<out String>?): PreparedStatement {
        TODO("Not yet implemented")
    }

    override fun prepareCall(sql: String?): CallableStatement {
        TODO("Not yet implemented")
    }

    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int): CallableStatement {
        TODO("Not yet implemented")
    }

    override fun prepareCall(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): CallableStatement {
        TODO("Not yet implemented")
    }

    override fun nativeSQL(sql: String?): String {
        throw UnsupportedOperationException("Native SQL is not supported by MkvConnection")
    }

    override fun setAutoCommit(autoCommit: Boolean) {
        throw UnsupportedOperationException("Commits is not supported by MkvConnection")
    }

    override fun getAutoCommit(): Boolean {
        throw UnsupportedOperationException("Commits is not supported by MkvConnection")
    }

    override fun commit() {
        throw UnsupportedOperationException("Commit is not supported by MkvConnection")
    }

    override fun rollback() {
        throw UnsupportedOperationException("Rollback is not supported by MkvConnection")
    }

    override fun rollback(savepoint: Savepoint?) {
        throw UnsupportedOperationException("Rollback is not supported by MkvConnection")
    }

    override fun isClosed(): Boolean {
        return false
    }

    override fun getMetaData(): DatabaseMetaData {
        return null
    }

    override fun setReadOnly(readOnly: Boolean) {
        this.readOnly = readOnly
    }

    override fun isReadOnly(): Boolean {
        return readOnly
    }

    override fun setCatalog(catalog: String?) {
        throw UnsupportedOperationException("setCatalog($catalog) is not supported by MkvConnection")
    }

    override fun getCatalog(): String {
        return "master"
    }

    override fun setTransactionIsolation(level: Int) {
    }

    override fun getTransactionIsolation(): Int {
        return 0
    }

    override fun getWarnings(): SQLWarning? {
        return null
    }

    override fun clearWarnings() {
    }

    override fun getTypeMap(): MutableMap<String, Class<*>> {
        return mutableMapOf()
    }

    override fun setTypeMap(map: MutableMap<String, Class<*>>?) {
    }

    override fun setHoldability(holdability: Int) {
    }

    override fun getHoldability(): Int {
        return 0
    }

    override fun setSavepoint(): Savepoint {
        throw OperationNotSupportedException("Savepoints are not supported by MkvConnection")
    }

    override fun setSavepoint(name: String?): Savepoint {
        throw OperationNotSupportedException("Savepoints are not supported by MkvConnection")
    }

    override fun releaseSavepoint(savepoint: Savepoint?) {
        throw OperationNotSupportedException("Savepoints are not supported by MkvConnection")
    }

    override fun createClob(): Clob {
        throw OperationNotSupportedException("createClob() is not supported by MkvConnection")
    }

    override fun createBlob(): Blob {
        throw OperationNotSupportedException("createBlob() is not supported by MkvConnection")
    }

    override fun createNClob(): NClob {
        throw OperationNotSupportedException("createNClob() is not supported by MkvConnection")
    }

    override fun createSQLXML(): SQLXML {
        throw OperationNotSupportedException("createSQLXML() is not supported by MkvConnection")
    }

    override fun isValid(timeout: Int): Boolean {
        return true
    }

    override fun setClientInfo(name: String?, value: String?) {
        throw OperationNotSupportedException("setClientInfo() is not supported by MkvConnection")
    }

    override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array {
        throw OperationNotSupportedException("createArrayOf($typeName) is not supported by MkvConnection")
    }

    override fun createStruct(typeName: String?, attributes: Array<out Any>?): Struct {
        throw OperationNotSupportedException("createStruct($typeName) is not supported by MkvConnection")
    }

    override fun setSchema(schema: String?) {
        throw OperationNotSupportedException("setSchema($schema) is not supported by MkvConnection")
    }

    override fun getSchema(): String {
        return "master"
    }

    override fun abort(executor: Executor?) {
        throw OperationNotSupportedException("abort() is not supported by MkvConnection")
    }

    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) {
        networkTimeout = milliseconds / 1000
    }

    override fun getNetworkTimeout(): Int {
        return networkTimeout
    }

    /* Useless crap */

    override fun <T : Any?> unwrap(iface: Class<T>?): T {
        TODO("Not yet implemented")
    }

    override fun isWrapperFor(iface: Class<*>?): Boolean {
        TODO("Not yet implemented")
    }

    override fun setClientInfo(properties: Properties?) {
        throw OperationNotSupportedException("setClientInfo() is not supported by MkvConnection")
    }

    override fun getClientInfo(name: String?): String {
        return "ClientInfo"
    }

    override fun getClientInfo(): Properties {
        return Properties()
    }
}
